# Generated by Django 5.2.7 on 2025-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
