# Generated by Django 5.2.7 on 2025-10-29 09:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='페이지')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '책갈피',
                'verbose_name_plural': '책갈피들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ebook_thumbnails/', verbose_name='썸네일')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='가격')),
                ('total_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='총 평점')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰 수')),
                ('ebook_file', models.FileField(upload_to='ebooks/', verbose_name='전자책 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '전자책',
                'verbose_name_plural': '전자책들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('kakao', '카카오페이'), ('naver', '네이버페이'), ('paypal', '페이팔'), ('cart', '장바구니'), ('direct', '바로결제')], max_length=20, verbose_name='결제 방법')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='구매 가격')),
                ('is_completed', models.BooleanField(default=False, verbose_name='결제 완료')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
            ],
            options={
                'verbose_name': '구매',
                'verbose_name_plural': '구매들',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
                'ordering': ['-created_at'],
            },
        ),
    ]
